FIXED BUG FUNDOS ENCERRADOS

In [1]:
from pyspark.sql import SparkSession
spark_session = SparkSession.builder.getOrCreate()
from pyspark.sql import functions as F, types as T
import datetime
import sys
from pyspark.sql import DataFrame, Row, SparkSession
import datetime
from pyspark.sql.functions import col, trim, to_date, desc, last, rank
import os
from pyspark.sql.window import Window
import pyspark.sql.functions as F
from pyspark.sql.functions import *
from pyspark.sql.types import StringType

In [2]:
expected = spark_session.createDataFrame([
        ('256',  None, '2019-10-30', 'A', '311'),
        ('256', '256', '2019-10-31', 'A', '311'),
        ('311', '256', '2019-11-01', 'A', '311'),
        ('311', '311', '2019-11-02', 'A', '311'),
        ('273', '311', '2019-11-03', 'A', '273'),
        ('400', '273', '2019-11-04', 'A', '400'),
        ('256',  None, '2019-10-30', 'B', '312'),
        ('256', '256', '2019-10-31', 'B', '312'),
        ('312', '256', '2019-11-01', 'B', '312'),
        ('312', '312', '2019-11-02', 'B', '312'),
        ('312', '312', '2019-11-03', 'B', '312'),
        ('400', '312', '2019-11-04', 'B', '400'),
        ('400', '400', '2019-11-05', 'B', '400'),
        ('400', '400', '2019-11-06', 'B', '400'),
        ('273',  None, '2019-10-30', 'C', '273'),
        ('273', '273', '2019-10-31', 'C', '273'),
        ('273', '273', '2019-11-01', 'C', '273'),
        ('311', '273', '2019-11-02', 'C', '311'),
        ('311', '311', '2019-11-03', 'C', '311'),
        ('311', '311', '2019-11-04', 'C', '311')
    ],['codtipo', 'codtipo_anterior', 'data', 'codfundo', 'novo_codtipo'])

In [194]:
novo_tipo = spark_session.createDataFrame([
        ('280',  None,  '2019-10-01', 'D'),
        ('280', '280',  '2019-10-02', 'D'),
        ('193', '280',  '2019-10-03', 'D'),
        ('193', '193',  '2019-10-04', 'D'),
        ('311', '193',  '2019-10-05', 'D'),
        ('400',  None,  '2019-10-28', 'A'),
        ('400', '400',  '2019-10-29', 'A'),
        ('256', '400',  '2019-10-30', 'A'),
        ('256', '256', '2019-10-31', 'A'),
        ('311', '256', '2019-11-01', 'A'),
        ('311', '311', '2019-11-02', 'A'),
        ('256', '311', '2019-11-03', 'A'),
        ('256', '256', '2019-11-04', 'A'),
        ('400', '256', '2019-11-04', 'A'),
    
        ('256',  None, '2019-10-30', 'B'),
        ('256', '256', '2019-10-31', 'B'),
        ('312', '256', '2019-11-01', 'B'),
        ('312', '312', '2019-11-02', 'B'),
        ('312', '312', '2019-11-03', 'B'),
        ('400', '312', '2019-11-04', 'B'),
        ('400', '400', '2019-11-05', 'B'),
        ('400', '400', '2019-11-06', 'B'),
        ('273',  None, '2019-10-30', 'C'),
        ('273', '273', '2019-10-31', 'C'),
        ('273', '273', '2019-11-01', 'C'),
        ('311', '273', '2019-11-02', 'C'),
        ('311', '311', '2019-11-03', 'C'),
        ('311', '311', '2019-11-04', 'C'),
        ('256', None, '2019-11-04', 'E'),
        ('400', '256', '2019-11-05', 'E'),
        ('400', None, '2019-11-05', 'E'),
        ('256', None, '2019-11-05', 'E'),
        ('256', None, '2019-11-05', 'E'),
        ('256', None, '2019-11-05', 'E'),
        ('256', '400', '2019-11-06', 'E'),
        ('311', '256', '2019-11-07', 'E'),
    ],['codtipo', 'codtipo_anterior', 'data', 'codfundo'])

In [195]:
tipo_fundo = spark_session.createDataFrame([
        ('280', '2019-03-27', None),
        ('256', '2019-03-27', '2019-10-31'),
        ('193', '2019-03-27', '2019-10-04'),
        ('273', '2019-11-03',  None),
        ('311', '2019-11-01',  None),
        ('312', '2019-11-01',  None),
        ('400', '2019-11-01',  None),
    ],["tipo_fundo_codigo", "tipo_fundo_data_inicio","tipo_fundo_data_fim"])

In [196]:
def fundos_encerrados_novo_tipox(fato_movimento_transferencia_final, dim_tipo_fundo):
    fato_movimento_transferencia_final = fato_movimento_transferencia_final.alias('l').join( broadcast(dim_tipo_fundo).alias('r'),
        col('l.codtipo_anterior') == col('r.tipo_fundo_codigo') , 'left' )
    
    fato_movimento_transferencia_final = fato_movimento_transferencia_final.withColumn("aux_column",
        when(
                ( col('tipo_fundo_data_fim').isNotNull() ) & ( col('codtipo') != col('codtipo_anterior') )  
                , col("codtipo")
            ).otherwise(None)
    )
    window = Window.partitionBy( ["codfundo"] ).orderBy( desc('data') )
       
    
    fato_movimento_transferencia_final = fato_movimento_transferencia_final.withColumn("novo_codtipo",
                    F.first('aux_column', True).over(window))

    fato_movimento_transferencia_final = fato_movimento_transferencia_final.withColumn("test", 
            F.collect_list('aux_column').over(window))
    
    fato_movimento_transferencia_final = fato_movimento_transferencia_final\
        .withColumn( 'novo_codtipo', when( col('novo_codtipo').isNull(), 
            col('codtipo') ).otherwise( col('novo_codtipo') ) )                                                                                
    
    return fato_movimento_transferencia_final.drop('tipo_fundo_codigo')

In [197]:
fundos_encerrados_novo_tipox(novo_tipo, tipo_fundo).orderBy('codfundo', col('data').asc()).toPandas()

,codtipo,codtipo_anterior,data,codfundo,tipo_fundo_data_inicio,tipo_fundo_data_fim,aux_column,novo_codtipo,test
0,400,None,2019-10-28,A,None,None,None,400,"[400, 311]"
1,400,400,2019-10-29,A,2019-11-01,None,None,400,"[400, 311]"
2,256,400,2019-10-30,A,2019-11-01,None,None,400,"[400, 311]"
3,256,256,2019-10-31,A,2019-03-27,2019-10-31,None,400,"[400, 311]"
4,311,256,2019-11-01,A,2019-03-27,2019-10-31,311,400,"[400, 311]"
5,311,311,2019-11-02,A,2019-11-01,None,None,400,[400]
6,256,311,2019-11-03,A,2019-11-01,None,None,400,[400]
7,256,256,2019-11-04,A,2019-03-27,2019-10-31,None,400,[400]
8,400,256,2019-11-04,A,2019-03-27,2019-10-31,400,400,[400]
9,256,None,2019-10-30,B,None,None,None,312,[312]
10,256,256,2019-10-31,B,2019-03-27,2019-10-31,None,312,[312]
11,312,256,2019-11-01,B,2019-03-27,2019-10-31,312,312,[312]
12,312,312,2019-11-02,B,2019-11-01,None,None,312,[]
13,312,312,2019-11-03,B,2019-11-01,None,None,312,[]
14,400,312,2019-11-04,B,2019-11-01,None,None,400,[]
15,400,400,2019-11-05,B,2019-11-01,None,None,400,[]
16,400,400,2019-11-06,B,2019-11-01,None,None,400,[]
17,273,None,2019-10-30,C,None,None,None,273,[]
18,273,273,2019-10-31,C,2019-11-03,None,None,273,[]
19,273,273,2019-11-01,C,2019-11-03,None,None,273,[]
20,311,273,2019-11-02,C,2019-11-03,None,None,311,[]
21,311,311,2019-11-03,C,2019-11-01,None,None,311,[]
22,311,311,2019-11-04,C,2019-11-01,None,None,311,[]
23,280,None,2019-10-01,D,None,None,None,311,[311]
24,280,280,2019-10-02,D,2019-03-27,None,None,311,[311]
25,193,280,2019-10-03,D,2019-03-27,None,None,311,[311]
26,193,193,2019-10-04,D,2019-03-27,2019-10-04,None,311,[311]
27,311,193,2019-10-05,D,2019-03-27,2019-10-04,311,311,[311]
28,256,None,2019-11-04,E,None,None,None,311,"[311, 400]"
29,400,256,2019-11-05,E,2019-03-27,2019-10-31,400,311,"[311, 400]"
30,400,None,2019-11-05,E,None,None,None,311,"[311, 400]"
31,256,None,2019-11-05,E,None,None,None,311,"[311, 400]"
32,256,None,2019-11-05,E,None,None,None,311,"[311, 400]"
33,256,None,2019-11-05,E,None,None,None,311,"[311, 400]"
34,256,400,2019-11-06,E,2019-11-01,None,None,311,[311]
35,311,256,2019-11-07,E,2019-03-27,2019-10-31,311,311,[311]

In [7]:
expected.orderBy('codfundo', col('data').desc()).toPandas()

   codtipo codtipo_anterior        data codfundo novo_codtipo
0      400              273  2019-11-04        A          400
1      273              311  2019-11-03        A          273
2      311              311  2019-11-02        A          311
3      311              256  2019-11-01        A          311
4      256              256  2019-10-31        A          311
5      256             None  2019-10-30        A          311
6      400              400  2019-11-06        B          400
7      400              400  2019-11-05        B          400
8      400              312  2019-11-04        B          400
9      312              312  2019-11-03        B          312
10     312              312  2019-11-02        B          312
11     312              256  2019-11-01        B          312
12     256              256  2019-10-31        B          312
13     256             None  2019-10-30        B          312
14     311              311  2019-11-04        C          311
15     311              311  2019-11-03        C          311
16     311              273  2019-11-02        C          311
17     273              273  2019-11-01        C          273
18     273              273  2019-10-31        C          273
19     273             None  2019-10-30        C          273